### ISSUE TITLE
Implement Google News & Calendar APIs into mirror

### ISSUE THREAD

**Issue by brandonmanke** [brandonmanke/smart-mirror#2]
# TODO
Some basic goals to keep in mind.

- [x] ~~News API/RSS implementation - Not 100% sure - look into sources (i.e. [NYTimes](https://developer.nytimes.com/), Google?, CNN, etc.).~~
- [x] Google Calendar implementation - [link](https://developers.google.com/google-apps/calendar/overview)
- [ ] GitHub API? (optional) - [link](https://developer.github.com/v3/activity/notifications/)
