### ISSUE TITLE
Alexa implementation

### ISSUE THREAD

**Issue by brandonmanke** [brandonmanke/smart-mirror#3]
# TODO
- [x] Get Alexa up and running on Rasberry Pi
- [ ] Implement [Alexa Skills](https://developer.amazon.com/alexa-skills-kit)
- [ ] Add bash script that runs the mirror and all of the Alexa things on the pi?
